Package skeleton
adokter/suntools pull request #1
Opened 2023-05-23 13:51 UTC by PietrH

2023-05-23 13:51 UTC, PietrH commented
Do we want to add tests? Github actions for CMD R CHECK?

2023-05-23 14:22 UTC, adokter commented
Thanks @PietrH, enabling an automated R CMD CHECK would be great

2023-05-23 16:38 UTC, adokter requested changes

2023-05-24 07:13 UTC, PietrH commented on README.md
> +devtools::install_github("rsbivand/sunMaptools")
Agreed, this was done using `usethis::use_readme_md()` , I'm not sure why it didn't pick up on adokter/suntools instead.

2023-05-24 07:18 UTC, PietrH commented
Do we want to change the license to GPL3?

2023-05-24 07:30 UTC, PietrH commented
Some more things to consider:

- Switching to LGPL v3
- Author list
- Version numbering

2023-05-24 08:33 UTC, PietrH commented
I've added a placeholder test in e2e83fb64769ebf19042ef9d4c23e0c40e969f23 so we'll pass R-CMD-check. I've just implemented the examples from `sun-methods.Rd`

2023-05-30 20:19 UTC, adokter approved these changes

2023-05-30 20:19 UTC, merged